server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: french-naturalization-app

  datasource:
    url: jdbc:h2:mem:naturalizationdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/YOUR_FIREBASE_PROJECT_ID
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

firebase:
  credentials:
    path: classpath:firebase-adminsdk.json

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
